version: '3.1'
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
    ports:
      - "3308:3306"