CREATE TABLE labels_posts (
    LABEL_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    FOREIGN KEY (LABEL_ID) REFERENCES labels(ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES posts(ID) ON DELETE CASCADE,
    FOREIGN KEY (LABEL_ID) REFERENCES labels(ID) ON UPDATE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES posts(ID) ON UPDATE CASCADE
);