CREATE TABLE posts_writers (
    POST_ID INT NOT NULL,
    WRITER_ID INT NOT NULL,
    FOREIGN KEY (POST_ID) REFERENCES posts(ID) ON DELETE CASCADE,
    FOREIGN KEY (WRITER_ID) REFERENCES writers(ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES posts(ID) ON UPDATE CASCADE,
    FOREIGN KEY (WRITER_ID) REFERENCES writers(ID) ON UPDATE CASCADE
);